/**
 * Yantra metadata — shared between /yantras (gallery) and /yantras/[slug] (deep-view).
 *
 * Each entry maps a yantra slug to its SVG file, scholarly metadata, and
 * the siddhi folio it corresponds to.
 */

export interface YantraMeta {
  slug: string;
  file: string;
  title: string;
  sanskrit: string;
  tradition: string;
  caution: "high" | "moderate";
  source: string;
  sourceCitation: string;
  description: string;
  symbolism: string;
  bijaBreakdown: {
    east: string;
    south: string;
    west: string;
    north: string;
    center: string;
  };
  mantraRing: string;
  siddhiSlug: string;
  siddhiName: string;
}

export const YANTRAS: YantraMeta[] = [
  {
    slug: "sri-cakra",
    file: "/yantras/sri-cakra-yantra.svg",
    title: "Śrī Cakra",
    sanskrit: "श्रीचक्र — The Nine-Triangle Matrix",
    tradition: "Śrī Vidyā / Śākta",
    caution: "high",
    source: "Vāmakeśvara Tantra · Bhāvanā Upaniṣad",
    sourceCitation: "Vāmakeśvara Tantra / Nityāṣoḍaśikārṇava; Bhāvanā Upaniṣad; Śaṭ-Cakra-Nirūpaṇa. The canonical nine-triangle yantra of the Śrī Vidyā tradition.",
    description: "The most iconic tantric yantra: nine interlocking triangles (four Śiva, five Śakti) converging on the central bindu. The geometric body of Tripurasundarī.",
    symbolism: "The nine triangles are the cosmic matrix: Śiva (upward) and Śakti (downward) interlocking to produce the 43-fold field of manifestation. The 16- and 8-petalled lotuses are the petals of creation and dissolution. The central bindu is Ṣoḍaśī herself — the unmanifest source from which all form arises and into which all form dissolves.",
    bijaBreakdown: { east: "ॐ", south: "hrīṁ", west: "klīṁ", north: "sauḥ", center: "śrīṁ" },
    mantraRing: "oṃ śrīṁ hrīṁ aim̐ namaḥ",
    siddhiSlug: "shodashi-tripurasundari-sadhana",
    siddhiName: "Ṣoḍaśī / Tripurasundarī",
  },
  {
    slug: "dakshina-kali",
    file: "/yantras/dakshina-kali-yantra.svg",
    title: "Dakṣiṇa Kālī Yantra",
    sanskrit: "दक्षिणकाली यन्त्र",
    tradition: "Śākta / Mahāvidyā",
    caution: "high",
    source: "Karpūrādi Stotra · Kālī Tantra",
    sourceCitation: "Karpūrādi-Stotra with Vimalānanda commentary (Woodroffe TTS 9, 1953); Kālī Tantra (Mālavīya Chowkhamba + Dīkṣit editions); Todala Tantra ch. 6.",
    description: "The primary Kālī yantra: an inverted yoni-triangle with the tripuṇḍra (Śiva's mark) within, ringed by a 15-skull muṇḍamālā encoding the dissolution of the Sanskrit alphabet.",
    symbolism: "The inverted triangle is the yoni (the matrix of manifestation). The tripuṇḍra within signals Śiva's presence as the passive consciousness beneath Kālī's active power. The skull-garland encodes the sonic matrix from which manifestation arises — and its dissolution back into silence.",
    bijaBreakdown: { east: "ॐ", south: "krīṁ", west: "hrīṁ", north: "hūṃ", center: "krīṁ" },
    mantraRing: "oṃ krīṁ hrīṁ hūṃ dakṣiṇa kālike namaḥ",
    siddhiSlug: "dakshina-kali-sadhana",
    siddhiName: "Dakṣiṇa Kālī",
  },
  {
    slug: "guhyakali",
    file: "/yantras/guhyakali-yantra.svg",
    title: "Guhyakālī Yantra",
    sanskrit: "गुह्यकाली यन्त्र — The Secret Kālī",
    tradition: "Śākta-Kālī / Mahākāla Saṃhitā",
    caution: "high",
    source: "Mahākāla Saṃhitā (Guhyakālī Khaṇḍa)",
    sourceCitation: "Mahākāla Saṃhitā — Guhyakālī Khaṇḍa (6+ Internet Archive editions + Chaukhamba Surbharati 2-vol. printed edition, 917 pp.). The most elaborate Śākta-Kālī scripture.",
    description: "The most elaborate Śākta-Kālī yantra: 16+8 lotus rings, an 8-segment directional circle, a 10-pointed star (the ten arms), and a 50-dot pañcāśad-akṣara-mālā (the fifty-letter garland).",
    symbolism: "The 8-segment circle is the aṣṭa-dik-mātṛkā — the Goddess in her eight directional forms. The 10-pointed star is the daśa-bhuja (ten-armed) form. The 50-dot garland is the mātṛkā (the fifty letters of the Sanskrit alphabet), the sonic matrix from which manifestation arises. The bindu is Guhyakālī herself — the secret Kālī, the Goddess as the source of all sound and form.",
    bijaBreakdown: { east: "ॐ", south: "klīṁ", west: "hrīṁ", north: "hūṃ", center: "hrīṁ klīṁ hūṃ" },
    mantraRing: "oṃ hrīṁ klīṁ hūṃ guhyakālyai namaḥ",
    siddhiSlug: "guhyakali-sadhana",
    siddhiName: "Guhyakālī",
  },
  {
    slug: "tara-ugra",
    file: "/yantras/tara-ugra-yantra.svg",
    title: "Tārā (Ugra) Yantra",
    sanskrit: "उग्रतारा यन्त्र",
    tradition: "Śākta / Mahāvidyā",
    caution: "high",
    source: "Bṛhad Nīla Tantra · Tārā Tantra",
    sourceCitation: "Bṛhad Nīla Tantra (4 Internet Archive editions: Kak & Shastri 1938, DLI/JaiGyan, Madhusudan Kaul Chaukhamba and DLI); Tārā Tantra; Ekajaṭā Tārā Sādhana Tantra (Khandelwal 2001).",
    description: "The fierce Hindu Tārā yantra — distinct from the Tibetan Buddhist forms. Contains a śava (corpse) silhouette within the inverted triangle, distinguishing Ugra Tārā from Dakṣiṇa Kālī.",
    symbolism: "The corpse within the triangle is the Śava-āsana (corpse-seat) — the contemplative frame of the death-state, distinguishing the Hindu Ugra Tārā from the Tibetan Buddhist Tārā traditions. The severed-head garland is the muṇḍamālā, the dissolution of differentiated identity. The bindu is Ugra Tārā herself, the fierce protective form of the Goddess.",
    bijaBreakdown: { east: "ॐ", south: "strīṁ", west: "hrīṁ", north: "hūṃ", center: "strīṁ" },
    mantraRing: "oṃ hrīṁ strīṁ hūṃ phaṭ",
    siddhiSlug: "tara-ugra-sadhana",
    siddhiName: "Tārā (Ugra)",
  },
  {
    slug: "tripura-bhairavi",
    file: "/yantras/tripura-bhairavi-yantra.svg",
    title: "Tripura Bhairavī Yantra",
    sanskrit: "त्रिपुरभैरवी यन्त्र",
    tradition: "Śrī Vidyā / Śākta",
    caution: "high",
    source: "Śāradā Tilaka ch. 11 · Paraśurāma Kalpasūtra",
    sourceCitation: "Śāradā Tilaka ch. 11 (4 Internet Archive editions: Malaviya, Avalon 1933, DLI, Sri Satguru 1988); Paraśurāma Kalpa Sūtra (4 Internet Archive editions); Tripura Bhairavī Rahasya.",
    description: "The fierce-form Śrī Vidyā yantra: a sadbhūja-cakra (six-triangle interlock) simplified from the full Śrī Cakra, with a red-tinted bindu region signalling the awakened Kundalinī mode.",
    symbolism: "The sadbhūja-cakra (six-triangle interlock) is the fierce-form variant of the Śrī Cakra — the same Śiva-Śakti interplay in its transformative, Kundalinī-awakened register. The red-tinted bindu signals the awakened ascendant mode of the Goddess. The bindu is Tripura Bhairavī herself, the fierce culmination of the Śrī Vidyā graduated path.",
    bijaBreakdown: { east: "ॐ", south: "hrīṁ", west: "aim̐", north: "srīṁ", center: "aim̐ hrīṁ srīṁ" },
    mantraRing: "aim̐ hrīṁ srīṁ tripura bhairavyai namaḥ",
    siddhiSlug: "tripura-bhairavi-sadhana",
    siddhiName: "Tripura Bhairavī",
  },
  {
    slug: "bhuvaneshvari",
    file: "/yantras/bhuvaneshvari-yantra.svg",
    title: "Bhuvaneśvarī Yantra",
    sanskrit: "भुवनेश्वरी यन्त्र",
    tradition: "Śākta / Mahāvidyā",
    caution: "high",
    source: "Śāradā Tilaka · Śākta Praamoda",
    sourceCitation: "Śāradā Tilaka (4 Internet Archive editions); Bhuvaneśvarī Tantra (in Dīkṣit's paired Chinnamastā evam Bhuvaneśvarī Tantra Śāstra); Bhuvaneśvarī Aṣṭakam (Rudrayāmala); Śākta Praamoda.",
    description: "The 'Queen of the Universe' yantra: 16-petalled then 8-petalled lotus rings, enclosing an inverted yoni-triangle with the Bhuvaneśvarī bīja hrīṁ at the bindu.",
    symbolism: "The 16- and 8-petalled lotuses are the full field of manifestation. The inverted triangle is the yoni — the Goddess as the sovereign creative matrix from which the fourteen bhuvanas (worlds) arise. The bindu is Bhuvaneśvarī herself, the Queen seated at the heart of her kingdom.",
    bijaBreakdown: { east: "ॐ", south: "hrīṁ", west: "klīṁ", north: "sauḥ", center: "hrīṁ" },
    mantraRing: "hrīṁ bhuvaneśvaryai namaḥ",
    siddhiSlug: "bhuvaneshvari-sadhana",
    siddhiName: "Bhuvaneśvarī",
  },
  {
    slug: "kamala",
    file: "/yantras/kamala-yantra.svg",
    title: "Kamalā Yantra",
    sanskrit: "कमला यन्त्र — The Lotus Goddess",
    tradition: "Śākta / Mahāvidyā",
    caution: "moderate",
    source: "Kamalā Mahāvidyā · Śākta Praamoda",
    sourceCitation: "Kamalā Mahāvidyā (Goswami Prahlad Giri, Chowkhamba); Śākta Praamoda (3 editions); Daśa Mahāvidyā Tantra-Sāra (Yogiraj Yashpal); Mahābhāgavata Purāṇa.",
    description: "The benevolent lotus yantra: note the inverted lotus order (8 outer, 16 inner) — Kamalā's signature. Two small elephant silhouettes flank the central lotus, referencing the gaja-bathing iconography.",
    symbolism: "The 8-then-16 lotus order inverts the standard hierarchy, signalling the Goddess's playful reversal of cosmic structure. The two elephants are the gaja-bathing motif — the royal consecration of the Goddess by the cosmic elephants of the directions. The bindu is Kamalā herself, the abundant gift-bestowing form.",
    bijaBreakdown: { east: "ॐ", south: "hrīṁ", west: "klīṁ", north: "sauḥ", center: "srīṁ" },
    mantraRing: "aim̐ hrīṁ srīṁ kamalāyai namaḥ",
    siddhiSlug: "kamala-sadhana",
    siddhiName: "Kamalā",
  },
  {
    slug: "dhumavati",
    file: "/yantras/dhumavati-yantra.svg",
    title: "Dhūmāvatī Yantra",
    sanskrit: "धूमावती यन्त्र — The Smoke-Clad Widow",
    tradition: "Śākta / Mahāvidyā",
    caution: "high",
    source: "Dhūmāvatī Tantra · Śākta Praamoda",
    sourceCitation: "Dhūmāvatī Tantra (Sanskrit, Internet Archive); Śākta Praamoda (Rājadevanandan & Devnandan Singh editions); Dhumāvatī Rahasya (Ashok Gaud).",
    description: "The deliberately inauspicious yantra: an asymmetric inverted triangle (the alakṣmī form) in rose accent, with a crow silhouette (the vāhana of death and liminal spaces) above the bindu.",
    symbolism: "The asymmetry of the triangle encodes the deliberate inauspiciousness — the Goddess in her aspect of all-that-is-rejected (decay, hunger, widowhood, ugliness). The crow is the vāhana of death and liminal spaces. The bindu is Dhūmāvatī herself, the wisdom that arises through direct confrontation with what society wards off.",
    bijaBreakdown: { east: "ॐ", south: "dhūṁ", west: "hrīṁ", north: "phaṭ", center: "dhūṁ" },
    mantraRing: "dhūṁ dhūmāvatyai namaḥ",
    siddhiSlug: "dhumavati-sadhana",
    siddhiName: "Dhūmāvatī",
  },
  {
    slug: "matangi",
    file: "/yantras/matangi-yantra.svg",
    title: "Mātaṅgī Yantra (Ucchiṣṭa Caṇḍālinī)",
    sanskrit: "मातङ्गी यन्त्र",
    tradition: "Śākta / Mahāvidyā",
    caution: "high",
    source: "Gandharva Tantra · Śākta Praamoda",
    sourceCitation: "Gandharva Tantra (Kak & Shastri 1934 ed., Internet Archive); Mātaṅgī Mahāvidyā (Goswami Prahlad Giri); Śākta Praamoda.",
    description: "The transgressive yantra: a bowl-with-offering (the ucchiṣṭa motif) below the bindu, encoding the deliberate inversion of purity protocol. The Goddess of the marginal and the rejected.",
    symbolism: "The ucchiṣṭa-bowl motif is the contemplative instrument — the deliberate inversion of purity protocol signalling that Mātaṅgī embodies the wisdom accessible through the marginalised, the rejected, and the leftover. The bindu is Mātaṅgī herself, the outcaste Goddess who grants mastery over all forms of expression.",
    bijaBreakdown: { east: "ॐ", south: "aim̐", west: "hrīṁ", north: "hūṃ", center: "aim̐" },
    mantraRing: "oṃ hrīṁ aim̐ mātaṅgyai namaḥ",
    siddhiSlug: "matangi-sadhana",
    siddhiName: "Mātaṅgī",
  },
  {
    slug: "smasana-bhairavi",
    file: "/yantras/smasana-bhairavi-yantra.svg",
    title: "Smāśāna Bhairavī Yantra",
    sanskrit: "श्मशानभैरवी यन्त्र",
    tradition: "Śaiva-Śākta / Bhairavī strand",
    caution: "high",
    source: "Brahmayāmala Tantra · Jayadrathayāmala",
    sourceCitation: "Brahmayāmala Tantra (Hatley 2018 critical edition, IPA); Jayadrathayāmala; Hatley 2007 PhD thesis (full PDF available).",
    description: "The cremation-ground yantra: rose-tinted bhūpura (the only yantra with this), scattered skull-and-crossbones motifs, and three nested funeral-pyre flames above the triangle.",
    symbolism: "The rose-tinted bhūpura is the śmaśāna (cremation ground) itself — the liminal space where the dissolution of form is most directly visible. The skull-and-crossbones motifs are the death-field iconography. The funeral-pyre flames are the transformative aspect. The bindu is Smāśāna Bhairavī herself, the Goddess in her most liminal aspect — the wisdom of the death-frame.",
    bijaBreakdown: { east: "ॐ", south: "hūṃ", west: "hrīṁ", north: "phaṭ", center: "hrīṁ hūṃ" },
    mantraRing: "oṃ hrīṁ hūṃ smāśāna bhairavyai namaḥ",
    siddhiSlug: "smasana-bhairavi-sadhana",
    siddhiName: "Smāśāna Bhairavī",
  },
  {
    slug: "preta-sandhi",
    file: "/yantras/preta-sandhi-yantra.svg",
    title: "Preta-Sandhi Yantra",
    sanskrit: "प्रेतसन्धि यन्त्र — Seal of Truce",
    tradition: "Tantra / Aghora / Kaula",
    caution: "high",
    source: "Preta-Siddhi Field Manual",
    sourceCitation: "Preta-Siddhi Field Manual (user-supplied transcription of Aghora/Kaula preta-saṁvāda operational rite). Sanskrit transmission artifacts flagged in the manual's editorial-correction table.",
    description: "The seal of truce between the human seeker and the preta: a 12×12-unit square bhūpura with four 2-unit gates, the śaṭkoṇa (six-pointed star), and a central black bindu (the preta's anchoring point).",
    symbolism: "The four gates are the open-yet-protected channels of communication with the spirit realm. The śaṭkoṇa balances the human and spirit realms. The black bindu is the preta's anchoring point during the dialogue. The single-engagement constraint encodes the principle that each contact is unique and not to be repeated.",
    bijaBreakdown: { east: "ॐ", south: "ह्रं", west: "क्षौं", north: "फट्", center: "(black bindu)" },
    mantraRing: "oṃ pretasandhikarāya hrīṁ kṣauṁ phaṭ svāhā",
    siddhiSlug: "preta-siddhi",
    siddhiName: "Preta-Saṁvāda",
  },
  {
    slug: "sudarshana",
    file: "/yantras/sudarshana-yantra.svg",
    title: "Sudarśana Yantra",
    sanskrit: "सुदर्शन यन्त्र — The Discus of Viṣṇu",
    tradition: "Śrī Vaiṣṇava / Pāñcarātra",
    caution: "moderate",
    source: "Ahirbudhnya Saṃhitā",
    sourceCitation: "Ahirbudhnya Saṃhitā (Pāñcarātra, c. 6th-9th c., Internet Archive); F. Otto Schrader, Introduction to the Pāñcarātra and the Ahirbudhnya Saṃhitā (1916).",
    description: "The Pāñcarātra protective yantra: 16-petalled outer lotus, 8-petalled inner lotus, and a central discus with 24 serrations (the flame-edge) and the bīja hrauṁ at the bindu.",
    symbolism: "The discus (cakra) is the active, protective aspect of Viṣṇu — the instrument of dharma-protection and the dissolution of adversity. The 24 serrations correspond to the 24 hours of the day and the unbroken vigilance of dharma. The 8-petalled lotus is the centre of operation; the 16-petalled lotus is the field of application.",
    bijaBreakdown: { east: "ॐ", south: "ह्रीं", west: "क्लीं", north: "सौः", center: "hrauṁ" },
    mantraRing: "oṃ namo nārāyaṇāya",
    siddhiSlug: "sudarshana-chakra-sadhana",
    siddhiName: "Sudarśana Chakra",
  },
  {
    slug: "bala-tripurasundari",
    file: "/yantras/bala-tripurasundari-yantra.svg",
    title: "Bālā Tripurasundarī Yantra",
    sanskrit: "बालात्रिपुरसुन्दरी यन्त्र",
    tradition: "Śrī Vidyā / Śākta",
    caution: "high",
    source: "Vāmakeśvara Tantra · Paraśurāma Kalpasūtra",
    sourceCitation: "Vāmakeśvara Tantra; Paraśurāma Kalpa Sūtra (4 Internet Archive editions) + Rāmeśvara Sūtri commentary; S.K. Ramachandra Rao, Śrī Vidyā (1998).",
    description: "The Bālā yantra is a simplified Śrī Cakra variant — three interlocking triangles (two Śiva + one Śakti) instead of the full nine, with a single 8-petalled lotus. The entry-level Śrī Vidyā yantra.",
    symbolism: "The simplified three-triangle interlock (vs. the full Śrī Cakra's nine) signals the entry-level register of Bālā — the girl-form of the Goddess, the approachable foundation before the full pañcadaśākṣarī. The cyan accent marks the Śrī Vidyā lineage. The bindu is Bālā herself, the gentle form that matures into the full Tripurasundarī.",
    bijaBreakdown: { east: "ॐ", south: "hrīṁ", west: "klīṁ", north: "sauḥ", center: "aim̐" },
    mantraRing: "oṃ aim̐ hrīṁ srīṁ bālāyai namaḥ",
    siddhiSlug: "bala-tripurasundari-sadhana",
    siddhiName: "Bālā Tripurasundarī",
  },
  {
    slug: "bagalamukhi",
    file: "/yantras/bagalamukhi-yantra.svg",
    title: "Bagalāmukhī Yantra",
    sanskrit: "बगलामुखी यन्त्र",
    tradition: "Śākta / Mahāvidyā",
    caution: "high",
    source: "Todala Tantra · Rudrayāmala",
    sourceCitation: "Todala Tantra ch. 6 (mūla-mantras of the 10 Mahāvidyās); Rudrayāmala (Bagalāmukhī-stotra section); Bagalāmukhī Rahasyam (Pitāmbarā Peeth, Datia, 1964).",
    description: "The eighth Mahāvidyā yantra: an inverted yoni-triangle with the Bagalāmukhī bīja hlīṁ at the bindu, and a stylized tongue-pulling motif within (referencing the iconography of the goddess pulling the demon's tongue).",
    symbolism: "The tongue-pulling motif encodes the stambhana power — the arrest of hostile speech and intent. The bright-gold accent throughout signals the Pitāmbarā ('yellow-clad') form of the Goddess. The bindu is Bagalāmukhī herself, the paralyser of inauspicious force.",
    bijaBreakdown: { east: "ॐ", south: "hlīṁ", west: "hrīṁ", north: "phaṭ", center: "hlīṁ" },
    mantraRing: "oṃ hlīṁ bagalāmukhī devyai namaḥ",
    siddhiSlug: "bagalamukhi-sadhana",
    siddhiName: "Bagalāmukhī",
  },
  {
    slug: "pratyangira",
    file: "/yantras/pratyangira-yantra.svg",
    title: "Pratyaṅgirā Yantra",
    sanskrit: "प्रत्यङ्गिरा यन्त्र",
    tradition: "Śākta / Atharvaṇa",
    caution: "high",
    source: "Atharvānokta Pratyaṅgirā Vidhāna · Pratyaṅgirā Kalpa",
    sourceCitation: "Atharvānokta Pratyaṅgirā Vidhāna (Sanskrit manuscript, Internet Archive); Pratyaṅgirā Kalpa; Viprīta Pratyaṅgirā Vidhānam; Hatley 2007 (Brahmayāmalatantra, milieu coverage).",
    description: "The Atharvaṇa protective yantra: a lion-face motif within an inverted yoni-triangle, surrounded by an 8-pointed star (aṣṭa-dala-cakra) in rose accent. The fierce protective form of the Goddess.",
    symbolism: "The lion-face motif signals the Narasiṃhī form — the Goddess as the lion-faced female counterpart of Narasiṃha, the protective avatāra of Viṣṇu. The 8-pointed star is the aṣṭa-dala-cakra, the protective ring. The rose accent marks the Atharvaṇa protective register. The bindu is Pratyaṅgirā herself, the neutraliser of hostile force.",
    bijaBreakdown: { east: "ॐ", south: "hrīṁ", west: "kṣauṁ", north: "phaṭ", center: "hrīṁ" },
    mantraRing: "oṃ hrīṁ pratyaṅgirāyai namaḥ",
    siddhiSlug: "pratyangira-devi-sadhana",
    siddhiName: "Pratyaṅgirā Devī",
  },
  {
    slug: "vajrayogini",
    file: "/yantras/vajrayogini-mandala.svg",
    title: "Vajravārāhī Maṇḍala",
    sanskrit: "वज्रवाराही मण्डल",
    tradition: "Buddhist Tantra / Cakrasaṃvara",
    caution: "high",
    source: "Śrī Vajravārāhīsādhana · Cakrasaṃvara-tantra",
    sourceCitation: "Śrī Vajravārāhīsādhana (Digital Sanskrit Buddhist Canon); Cakrasaṃvara-tantra; Elizabeth English, Vajrayoginī (Wisdom, 2002).",
    description: "The Buddhist tantric maṇḍala (circular, distinct from the Hindu square yantras): four concentric protective rings in purple accent, an 8-petalled lotus at the center, with the sow-head silhouette and kartari-kapāla (knife and skull-bowl) motifs flanking the Vajravārāhī bīja hrīṁ.",
    symbolism: "The circular form (vs. the Hindu square bhūpura) signals the Buddhist tantric register. The purple accent distinguishes it from the Hindu Śākta gold/rose palette. The sow-head (vārāhī) is the iconographic mark — the rooting-out of ignorance. The kartari (curved knife) and kapāla (skull bowl) are the standard Vajravārāhī attributes. The bindu is Vajravārāhī herself, the adamantine ḍākinī.",
    bijaBreakdown: { east: "ॐ", south: "hrīṁ", west: "hūṁ", north: "phaṭ", center: "hrīṁ" },
    mantraRing: "oṃ hrīṁ vajravārāhyai hūṃ phaṭ",
    siddhiSlug: "vajrayogini-sadhana",
    siddhiName: "Vajravārāhī / Vajrayoginī",
  },
  {
    slug: "lakulisha-linga",
    file: "/yantras/lakulisha-linga.svg",
    title: "Lakulīśa Liṅga",
    sanskrit: "लाकुलीश लिङ्ग",
    tradition: "Śaiva / Pāśupata",
    caution: "high",
    source: "Pāśupata Sūtras · Kauṇḍinya's Pañcārthabhāṣya",
    sourceCitation: "Pāśupata Sūtras with Kauṇḍinya's Pañcārthabhāṣya, Trivandrum Sanskrit Series 143 (1940, ed. Ananta Kṛṣṇa Śāstrī — 3 Internet Archive digitisations); Pashupat Sutram (Chakrapani Trivedi ed.); Ingalls 1962 (HJAS).",
    description: "An austere iconographic diagram (not a standard yantra — the Pāśupata path is conduct-centric, not mantra-centric). A central liṅga silhouette with the lakula (club) across its upper third, on a pīṭha (pedestal), with the pañcākṣara 'Namaḥ Śivāya' at the four gates.",
    symbolism: "The liṅga is the aniconic form of Śiva — the unmanifest sign. The club (lakula) is Lakulīśa's identifying attribute, signaling the historical founder of the Pāśupata order. The pañcākṣara at the four gates is the public mantra of the tradition. The diagram is a contemplative aid, not an activated ritual object — the Pāśupata path is undertaken through vows and conduct rather than yantra-pūjā.",
    bijaBreakdown: { east: "Namaḥ Śivāya", south: "Namaḥ Śivāya", west: "Namaḥ Śivāya", north: "Namaḥ Śivāya", center: "(liṅga)" },
    mantraRing: "(no outer mantra ring — the Pāśupata path is not mantra-centric)",
    siddhiSlug: "lakulisha-pashupata-sadhana",
    siddhiName: "Lakulīśa Pāśupata",
  },
  {
    slug: "nath-cakra",
    file: "/yantras/nath-cakra-diagram.svg",
    title: "Nāth Cakra Diagram",
    sanskrit: "नाथ चक्र — The Six-Cakra System",
    tradition: "Nāth / Śaiva-Yogic",
    caution: "high",
    source: "Kaulajñānanirṇaya · Śaṭ-Cakra-Nirūpaṇa",
    sourceCitation: "Kaulajñānanirṇaya (4 Internet Archive editions, attributed to Matsyendranāth); Śaṭ-Cakra-Nirūpaṇa (16th c., the standard later systematisation); Mallinson & Singleton, Roots of Yoga (2017).",
    description: "A diagram of the six-cakra system central to the Nāth tradition: six horizontal lotus-forms stacked along the central suṣumṇā nāḍī, from the 4-petalled mūlādhāra (base) to the 1000-petalled sahasrāra (crown). The iḍā and piṅgalā nāḍīs weave around the central axis in a double-helix pattern, with the So'ham breath-mantra inscribed vertically along the axis.",
    symbolism: "The six cakras are the astral-body framework that the Nāth tradition developed and bequeathed to later Haṭha Yoga: mūlādhāra (4 petals), svādhiṣṭhāna (6), maṇipūra (10), anāhata (12), viśuddha (16), ājñā (2), with sahasrāra (1000) above. The suṣumṇā is the central channel through which Kuṇḍalinī ascends. The iḍā (lunar, left) and piṅgalā (solar, right) weave around it. The So'ham ('I am That') is the breath-mantra — the public core practice of the Nāth tradition.",
    bijaBreakdown: { east: "(no gates — cakra diagram, not yantra)", south: "", west: "", north: "", center: "So'ham" },
    mantraRing: "(no outer mantra ring — cakra diagram, not yantra)",
    siddhiSlug: "matsyendranath-nath-sadhana",
    siddhiName: "Matsyendranāth / Nāth",
  },
];

export function getYantraBySlug(slug: string): YantraMeta | undefined {
  return YANTRAS.find((y) => y.slug === slug);
}
